#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

    - name: Cloning PlexGuide
      git:
        repo: "https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server"
        dest: /opt/plexguide
        version: "v8"
        force: yes
